version: 2
jobs:
  build:
    docker: # use the docker executor type
      - image: circleci/node:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: Install functions dependencies
          command: cd functions && npm install
      - run: 
          name: Deploy functions
          command: cd functions && ./node_modules/.bin/firebase deploy  --project pillar-voice --token=$FIREBASE_DEPLOY_TOKEN
      - run:
          name: Create Google Application Credential file
          command: echo "${GOOGLE_APPLICATION_CREDENTIALS_CONTENT}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: 
          name: Install dialogFlow dependencies
          command: cd dialogFlow && npm install
      - run: 
          name: Deploy dialogFlow
          command: node ./dialogFlow/deployAgent.js
      - run:
          name: Delete Google Application Credential file
          when: always
          command: rm "${GOOGLE_APPLICATION_CREDENTIALS}"
